### ISSUE TITLE
error when trying to run application

### ISSUE THREAD

**Issue by hikilaka** [eliellis/tinytheater#1]
zack@development:~/tinytheater$ node index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'Q'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/zack/tinytheater/lib/yts-api/yts-api.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/zack/tinytheater/index.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

Already tried npm install, the q package is there.

**Comment by eliellis** [comment]
i just attempted a clone and install on a virgin machine and i'm not experiencing this problem. my suggestion would be to clear the directory you're working inside, clone, and run `npm install` oncemore and see if your issue still occurs.

**Comment by eliellis** [comment]
i apologize. after attempting an install on another linux system i was given this same error. fixed in commit 44fe2bdd7ec174c564dfa4224993fc0d5a6c97c8.
